### ISSUE TITLE
what is the edition of the pytorch,pytorch 0.4.0 or pytorch 0.4.1?

### ISSUE THREAD

**Issue by mlx123** [L1aoXingyu/fcn.pytorch#2]
Hello
what is the edition of the pytorch,pytorch 0.4.0 or pytorch 0.4.1?
Sometimes the code can run well in one edition,but it doesnot go well in another edition.

Thanks

**Comment by L1aoXingyu** [comment]
0.4 or 1.0 may be OK. If you have any question about running these code, please don't hesitate to tell me.
